/**
 * mutation
 */
export const SET_SINGER = 'SET_SINGER'
export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLATLIST = 'SET_PLATLIST'
export const SET_SEQUENCELIST ='SET_SEQUENCELIST'
export const SET_MODE ='SET_MODE'
export const SET_CURRENTINDEX = 'SET_CURRENTINDEX'